In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('diabetes.csv')
data.head()


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [7]:
len(data)


768

In [9]:
data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [10]:
#Replace Zeroes

Zero_Not_Accepted = ['Glucose', 'BloodPressure', 'SkinThickness', 'BMI', 'Insulin']

for column in Zero_Not_Accepted:
    data[column] = data[column].replace(0,np.NaN)
    mean = int(data[column].mean(skipna=True))
    data[column] = data[column].replace(np.NaN,mean)

In [11]:
#Split dataset train and test dataset
feature_data = data.iloc[:,:-1].values
target_data  = data.iloc[:,-1].values

In [12]:
from sklearn.model_selection import train_test_split
feature_train,feature_test,target_train,target_test = train_test_split(feature_data,target_data,test_size=0.2,random_state = 0)



In [21]:
print(feature_train)
print(feature_test)
print(target_train)
print(target_test)

[[ 0.90832902  0.93641795  0.44764174 ...  0.36863635  0.67740401
   1.69955804]
 [ 0.03644676 -0.81630913 -1.05200558 ... -0.63294341 -0.07049698
  -0.96569189]
 [-1.12606292  1.43247278  1.44740662 ...  2.81535261 -0.11855487
  -0.88240283]
 ...
 [ 0.03644676 -0.91552009 -0.63543688 ... -1.13373329 -0.95656442
  -1.04898095]
 [ 2.0708387  -1.21315299  0.11438678 ... -0.36108605 -0.50001442
   0.11706589]
 [ 0.32707418  0.47343344  0.7808967  ... -0.08922869  0.52121586
   2.94889395]]
[[-0.89295432  2.48519445  0.36928267 ...  1.75900682  2.78935129
  -0.93064283]
 [-0.56553774 -0.47166102  0.2077215  ...  0.29022792 -0.27698825
  -0.83598035]
 [ 0.08929543 -1.46799276 -0.76164551 ...  0.35340121 -0.31725331
  -0.64665539]
 ...
 [ 0.08929543  0.65322965  1.17708851 ...  1.93273336  0.4694641
  -0.93064283]
 [-0.23812115 -0.18240342  0.2077215  ... -0.86268455 -1.19689011
  -0.74131787]
 [-0.89295432 -0.47166102  0.04616033 ... -0.15198508  1.01459113
  -0.74131787]]
[1 0 0 0 1 1 1 1 

In [13]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler

Sc_data = StandardScaler()
feature_train = Sc_data.fit_transform(feature_train)
feature_test  = Sc_data.fit_transform(feature_test)

In [14]:
#Define the Model
#KNN Machine Learning Model
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 11,p=2,metric='euclidean')
classifier.fit(feature_train,target_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=11)

In [15]:
#Predict the test set result
target_predict = classifier.predict(feature_test)
target_predict

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [61]:
#Evaluating the model
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(target_test,target_predict)
cm

array([[95, 12],
       [18, 29]], dtype=int64)

In [18]:
from sklearn.metrics import f1_score
print(f1_score(target_test,target_predict))

0.6590909090909092


In [62]:
from sklearn.metrics import accuracy_score
print(accuracy_score(target_test,target_predict))

0.8051948051948052


In [75]:
pr1 =model.predict(x.loc[2,:].to_numpy().reshape(1,-1))

In [76]:
pr1

array([1], dtype=int64)

In [78]:
pr2=model.predict(x.loc[3,:].to_numpy().reshape(1,-1))
pr2

array([0], dtype=int64)

In [22]:
#Normalization
x = (data -np.min(data))/(np.max(data)-np.min(data)).values


In [23]:
y = data.Outcome.values
data = data.drop(['Outcome'], axis=1)

In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15, random_state=42)


In [25]:
# Naive Bayes Machine Learning Model
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train,y_train)

MultinomialNB()

In [63]:
#prediction = dict()
prediction = model.predict(x_test)

In [64]:
prediction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0], dtype=int64)

In [65]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(y_test,prediction)

1.0

In [66]:
print(classification_report(y_test, prediction, target_names = ["not_Diabetes", "diabetes"]))

              precision    recall  f1-score   support

not_Diabetes       1.00      1.00      1.00        76
    diabetes       1.00      1.00      1.00        40

    accuracy                           1.00       116
   macro avg       1.00      1.00      1.00       116
weighted avg       1.00      1.00      1.00       116



In [82]:
# Model Accuracy, how often is the classifier correct?
from sklearn import metrics

In [70]:
print("Accuracy:",metrics.accuracy_score(y_test, prediction))

Accuracy: 1.0


In [71]:
#Prediction on single dataset
predicted =model.predict(x.loc[2,:].to_numpy().reshape(1,-1))

In [72]:
predicted

array([1], dtype=int64)

In [73]:
pred = model.predict(x.loc[3,:].to_numpy().reshape(1,-1))

In [74]:
pred

array([0], dtype=int64)